
management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: env, mappings, health
    enabled-by-default: true

---
spring:
  profiles: dev
server:
  port: 8080